[features]
seeds = false
skip-lint = false

[programs.devnet]
quantum-vault = "6tLhtJ5vr4R2KF4xoDodQmuWKvGPm1orXRqvtTNy5P3t"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
